[[CURRENCIES]]
code="MATRIX"
issuer="GAD52KSDKX5QX4VW5A3FBXB6PXCOCTUBRUW6Q4XTEPLG6WV3ZRCVTX6P"
display_decimals=7
name="MATRIX PiChain"
desc="The most super advanced smart stablecoin for PiChain"
image="https://raw.githubusercontent.com/KOSASIH/matrix-pichain/main/logo.png"
anchor="KOSASIH"
anchor_asset="MATRIX"
anchor_asset_type="smart_stablecoin"
